DefaultMax:100
AlertRate: 60
DefaultMax: 100
HeatBlocks:
    - lava
        Type:'LAVA'
        Rate:2
        Range:5
CoolBlocks:
    - ice
        Type:'ICE'
        Rate:3
        Range:5
Effects:
    FROST:
        - nausea
            Type:'CONFUSION'
            Duration: 20
            Power: 100
            Threshold: 4
Armor:
    FROST:
        - superhelm
            ID:'LEATHER_CHESTPLATE'
            Color:511
            Name:'Super Helm'
            Lore:
            Amount:5